# db/seeds/exercises.rb

# frozen_string_literal: true

# rubocop:disable Layout/LineLength
EXERCISES = [
  # Chest
  { name: "Assisted Dip", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Machine", description: "A compound exercise that works the chest, shoulders, and triceps with assistance." },
  { name: "Band-Assisted Bench Press", categories: ["Chest"], equipment_type: "Resistance Band", description: "A variation of the bench press with band assistance." },
  { name: "Bar Dip", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A compound exercise that works the chest, shoulders, and triceps." },
  { name: "Bench Press", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Barbell", description: "A compound exercise that works the chest, shoulders, and triceps." },
  { name: "Bench Press Against Band", categories: ["Chest"], equipment_type: "Resistance Band", description: "A variation of the bench press with band resistance." },
  { name: "Board Press", categories: ["Chest", "Triceps"], equipment_type: "Barbell", description: "A variation of the bench press that limits range of motion." },
  { name: "Cable Chest Press", categories: ["Chest"], equipment_type: "Cable", description: "A compound exercise that works the chest with constant tension." },
  { name: "Close-Grip Bench Press", categories: ["Chest", "Triceps"], equipment_type: "Barbell", description: "A variation of the bench press that emphasizes the triceps." },
  { name: "Close-Grip Feet-Up Bench Press", categories: ["Chest", "Triceps"], equipment_type: "Barbell", description: "A variation of the bench press with feet elevated." },
  { name: "Decline Bench Press", categories: ["Chest"], equipment_type: "Barbell", description: "A variation of the bench press that emphasizes the lower chest." },
  { name: "Decline Push-Up", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A variation of the push-up that emphasizes the lower chest." },
  { name: "Dumbbell Chest Fly", categories: ["Chest"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the chest muscles." },
  { name: "Dumbbell Chest Press", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Dumbbell", description: "A compound exercise that works the chest, shoulders, and triceps." },
  { name: "Dumbbell Decline Chest Press", categories: ["Chest"], equipment_type: "Dumbbell", description: "A variation of the chest press that emphasizes the lower chest." },
  { name: "Dumbbell Floor Press", categories: ["Chest", "Triceps"], equipment_type: "Dumbbell", description: "A variation of the chest press performed on the floor." },
  { name: "Dumbbell Pullover", categories: ["Chest", "Back"], equipment_type: "Dumbbell", description: "An exercise that works the chest and lats." },
  { name: "Feet-Up Bench Press", categories: ["Chest", "Triceps"], equipment_type: "Barbell", description: "A variation of the bench press with feet elevated." },
  { name: "Floor Press", categories: ["Chest", "Triceps"], equipment_type: "Barbell", description: "A variation of the bench press performed on the floor." },
  { name: "Incline Bench Press", categories: ["Chest", "Shoulder"], equipment_type: "Barbell", description: "A variation of the bench press that emphasizes the upper chest." },
  { name: "Incline Dumbbell Press", categories: ["Chest", "Shoulder"], equipment_type: "Dumbbell", description: "A variation of the chest press that emphasizes the upper chest." },
  { name: "Incline Push-Up", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A variation of the push-up that emphasizes the upper chest." },
  { name: "Kettlebell Floor Press", categories: ["Chest", "Triceps"], equipment_type: "Kettlebell", description: "A variation of the chest press performed on the floor." },
  { name: "Kneeling Incline Push-Up", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A variation of the push-up performed on knees." },
  { name: "Kneeling Push-Up", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A variation of the push-up performed on knees." },
  { name: "Machine Chest Fly", categories: ["Chest"], equipment_type: "Machine", description: "An isolation exercise that targets the chest muscles." },
  { name: "Machine Chest Press", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Machine", description: "A compound exercise that works the chest, shoulders, and triceps." },
  { name: "Pec Deck", categories: ["Chest"], equipment_type: "Machine", description: "An isolation exercise that targets the chest muscles." },
  { name: "Pin Bench Press", categories: ["Chest", "Triceps"], equipment_type: "Barbell", description: "A variation of the bench press with pins for safety." },
  { name: "Push-Up", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A compound exercise that works the chest, shoulders, and triceps." },
  { name: "Push-Up Against Wall", categories: ["Chest", "Shoulder"], equipment_type: "Bodyweight", description: "A variation of the push-up performed against a wall." },
  { name: "Push-Ups With Feet in Rings", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A variation of the push-up with feet in rings." },
  { name: "Resistance Band Chest Fly", categories: ["Chest"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the chest muscles." },
  { name: "Ring Dip", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A compound exercise that works the chest, shoulders, and triceps." },
  { name: "Smith Machine Bench Press", categories: ["Chest", "Shoulder", "Triceps"], equipment_type: "Machine", description: "A variation of the bench press using a Smith machine." },
  { name: "Smith Machine Incline Bench Press", categories: ["Chest", "Shoulder"], equipment_type: "Machine", description: "A variation of the incline bench press using a Smith machine." },
  { name: "Smith Machine Reverse Grip Bench Press", categories: ["Chest", "Triceps"], equipment_type: "Machine", description: "A variation of the bench press with reverse grip." },
  { name: "Standing Cable Chest Fly", categories: ["Chest"], equipment_type: "Cable", description: "An isolation exercise that targets the chest muscles." },
  { name: "Standing Resistance Band Chest Fly", categories: ["Chest"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the chest muscles." },

  # Shoulder
  { name: "Arnold Press", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "A variation of the shoulder press that emphasizes the anterior deltoids." },
  { name: "Band External Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Band Internal Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Band Pull-Apart", categories: ["Shoulder", "Back"], equipment_type: "Resistance Band", description: "An exercise that targets the rear deltoids and upper back." },
  { name: "Barbell Front Raise", categories: ["Shoulder"], equipment_type: "Barbell", description: "An isolation exercise that targets the anterior deltoids." },
  { name: "Barbell Rear Delt Row", categories: ["Shoulder", "Back"], equipment_type: "Barbell", description: "A compound exercise that works the rear deltoids and upper back." },
  { name: "Barbell Upright Row", categories: ["Shoulder", "Back"], equipment_type: "Barbell", description: "A compound exercise that works the shoulders and traps." },
  { name: "Behind the Neck Press", categories: ["Shoulder", "Triceps"], equipment_type: "Barbell", description: "A variation of the overhead press performed behind the neck." },
  { name: "Cable Internal Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Cable", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Cable Lateral Raise", categories: ["Shoulder"], equipment_type: "Cable", description: "An isolation exercise that targets the lateral deltoids." },
  { name: "Cable Rear Delt Row", categories: ["Shoulder", "Back"], equipment_type: "Cable", description: "A compound exercise that works the rear deltoids and upper back." },
  { name: "Cuban Press", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "A complex movement that works the shoulders and rotator cuff." },
  { name: "Dumbbell Front Raise", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the anterior deltoids." },
  { name: "Dumbbell Horizontal Internal Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Dumbbell Horizontal External Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Dumbbell Lateral Raise", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the lateral deltoids." },
  { name: "Dumbbell Rear Delt Row", categories: ["Shoulder", "Back"], equipment_type: "Dumbbell", description: "A compound exercise that works the rear deltoids and upper back." },
  { name: "Dumbbell Shoulder Press", categories: ["Shoulder", "Triceps"], equipment_type: "Dumbbell", description: "A compound exercise that works the shoulders and triceps." },
  { name: "Face Pull", categories: ["Shoulder", "Back"], equipment_type: "Cable", description: "An exercise that targets the rear deltoids and upper back." },
  { name: "Front Hold", categories: ["Shoulder", "Abs"], equipment_type: "Bodyweight", description: "An isometric exercise that works the shoulders." },
  { name: "Handstand Push-Up", categories: ["Shoulder", "Triceps"], equipment_type: "Bodyweight", description: "A compound exercise that works the shoulders and triceps." },
  { name: "Landmine Press", categories: ["Shoulder", "Chest"], equipment_type: "Barbell", description: "A variation of the shoulder press using a landmine." },
  { name: "Lying Dumbbell External Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Lying Dumbbell Internal Shoulder Rotation", categories: ["Shoulder"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the rotator cuff." },
  { name: "Machine Lateral Raise", categories: ["Shoulder"], equipment_type: "Machine", description: "An isolation exercise that targets the lateral deltoids." },
  { name: "Machine Shoulder Press", categories: ["Shoulder", "Triceps"], equipment_type: "Machine", description: "A compound exercise that works the shoulders and triceps." },
  { name: "Monkey Row", categories: ["Shoulder", "Back"], equipment_type: "Bodyweight", description: "A compound exercise that works the shoulders and back." },
  { name: "One-Arm Landmine Press", categories: ["Shoulder", "Chest"], equipment_type: "Barbell", description: "A unilateral variation of the landmine press." },
  { name: "Overhead Press", categories: ["Shoulder", "Triceps"], equipment_type: "Barbell", description: "A compound exercise that works the shoulders and triceps." },
  { name: "Plate Front Raise", categories: ["Shoulder"], equipment_type: "Bodyweight", description: "An isolation exercise that targets the anterior deltoids." },
  { name: "Power Jerk", categories: ["Shoulder", "Legs"], equipment_type: "Barbell", description: "A dynamic overhead pressing movement." },
  { name: "Push Press", categories: ["Shoulder", "Legs"], equipment_type: "Barbell", description: "A dynamic overhead pressing movement." },
  { name: "Reverse Cable Flyes", categories: ["Shoulder", "Back"], equipment_type: "Cable", description: "An isolation exercise that targets the rear deltoids." },
  { name: "Reverse Dumbbell Flyes", categories: ["Shoulder", "Back"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the rear deltoids." },
  { name: "Reverse Machine Fly", categories: ["Shoulder", "Back"], equipment_type: "Machine", description: "An isolation exercise that targets the rear deltoids." },
  { name: "Seated Dumbbell Shoulder Press", categories: ["Shoulder", "Triceps"], equipment_type: "Dumbbell", description: "A variation of the shoulder press performed seated." },
  { name: "Seated Barbell Overhead Press", categories: ["Shoulder", "Triceps"], equipment_type: "Barbell", description: "A variation of the overhead press performed seated." },
  { name: "Seated Smith Machine Shoulder Press", categories: ["Shoulder", "Triceps"], equipment_type: "Machine", description: "A variation of the shoulder press using a Smith machine." },
  { name: "Snatch Grip Behind the Neck Press", categories: ["Shoulder", "Triceps"], equipment_type: "Barbell", description: "A variation of the overhead press with snatch grip." },
  { name: "Squat Jerk", categories: ["Shoulder", "Legs"], equipment_type: "Barbell", description: "A dynamic overhead pressing movement." },
  { name: "Split Jerk", categories: ["Shoulder", "Legs"], equipment_type: "Barbell", description: "A dynamic overhead pressing movement." },

  # Biceps
  { name: "Barbell Curl", categories: ["Biceps"], equipment_type: "Barbell", description: "An isolation exercise that targets the biceps." },
  { name: "Barbell Preacher Curl", categories: ["Biceps"], equipment_type: "Barbell", description: "An isolation exercise that targets the biceps with strict form." },
  { name: "Bayesian Curl", categories: ["Biceps"], equipment_type: "Dumbbell", description: "A variation of the bicep curl that emphasizes the brachialis." },
  { name: "Bodyweight Curl", categories: ["Biceps"], equipment_type: "Bodyweight", description: "A bodyweight variation of the bicep curl." },
  { name: "Cable Crossover Bicep Curl", categories: ["Biceps"], equipment_type: "Cable", description: "An isolation exercise that targets the biceps with cables." },
  { name: "Cable Curl With Bar", categories: ["Biceps"], equipment_type: "Cable", description: "An isolation exercise that targets the biceps with a bar attachment." },
  { name: "Cable Curl With Rope", categories: ["Biceps"], equipment_type: "Cable", description: "An isolation exercise that targets the biceps with a rope attachment." },
  { name: "Concentration Curl", categories: ["Biceps"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the biceps with strict form." },
  { name: "Drag Curl", categories: ["Biceps"], equipment_type: "Barbell", description: "A variation of the bicep curl that emphasizes the upper biceps." },
  { name: "Dumbbell Curl", categories: ["Biceps"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the biceps." },
  { name: "Dumbbell Preacher Curl", categories: ["Biceps"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the biceps with strict form." },
  { name: "Hammer Curl", categories: ["Biceps", "Forearm Extensors"], equipment_type: "Dumbbell", description: "A variation of the bicep curl that emphasizes the brachialis." },
  { name: "Incline Dumbbell Curl", categories: ["Biceps"], equipment_type: "Dumbbell", description: "A variation of the bicep curl that emphasizes the long head of the biceps." },
  { name: "Machine Bicep Curl", categories: ["Biceps"], equipment_type: "Machine", description: "An isolation exercise that targets the biceps." },
  { name: "Resistance Band Curl", categories: ["Biceps"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the biceps." },
  { name: "Spider Curl", categories: ["Biceps"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the biceps with strict form." },

  # Triceps
  { name: "Barbell Standing Triceps Extension", categories: ["Triceps"], equipment_type: "Barbell", description: "An isolation exercise that targets the triceps." },
  { name: "Barbell Incline Triceps Extension", categories: ["Triceps"], equipment_type: "Barbell", description: "A variation of the triceps extension performed on an incline." },
  { name: "Barbell Lying Triceps Extension", categories: ["Triceps"], equipment_type: "Barbell", description: "An isolation exercise that targets the triceps." },
  { name: "Bench Dip", categories: ["Triceps", "Chest", "Shoulder"], equipment_type: "Bodyweight", description: "A compound exercise that works the triceps and chest." },
  { name: "Crossbody Cable Triceps Extension", categories: ["Triceps"], equipment_type: "Cable", description: "An isolation exercise that targets the triceps." },
  { name: "Close-Grip Push-Up", categories: ["Triceps", "Chest", "Shoulder"], equipment_type: "Bodyweight", description: "A compound exercise that emphasizes the triceps." },
  { name: "Dumbbell Lying Triceps Extension", categories: ["Triceps"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the triceps." },
  { name: "Dumbbell Standing Triceps Extension", categories: ["Triceps"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the triceps." },
  { name: "Overhead Cable Triceps Extension", categories: ["Triceps"], equipment_type: "Cable", description: "An isolation exercise that targets the long head of the triceps." },
  { name: "Tate Press", categories: ["Triceps", "Chest"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the triceps." },
  { name: "Tricep Bodyweight Extension", categories: ["Triceps"], equipment_type: "Bodyweight", description: "A bodyweight variation of the triceps extension." },
  { name: "Tricep Pushdown With Bar", categories: ["Triceps"], equipment_type: "Cable", description: "An isolation exercise that targets the triceps with a bar attachment." },
  { name: "Tricep Pushdown With Rope", categories: ["Triceps"], equipment_type: "Cable", description: "An isolation exercise that targets the triceps with a rope attachment." },

  # Legs
  { name: "Barbell Front Squat", categories: ["Legs", "Abs"], equipment_type: "Barbell", description: "A compound exercise that targets the quadriceps and core." },
  { name: "Barbell Hack Squat", categories: ["Legs"], equipment_type: "Barbell", description: "A compound exercise that targets the quadriceps." },
  { name: "Barbell Lunge", categories: ["Legs", "Glute"], equipment_type: "Barbell", description: "A compound exercise that targets the quadriceps and glutes." },
  { name: "Barbell Squat", categories: ["Legs", "Glute", "Back"], equipment_type: "Barbell", description: "A compound exercise that targets the quadriceps, hamstrings, and glutes." },
  { name: "Bodyweight Squat", categories: ["Legs", "Glute"], equipment_type: "Bodyweight", description: "A compound exercise that targets the lower body." },
  { name: "Bulgarian Split Squat", categories: ["Legs", "Glute"], equipment_type: "Dumbbell", description: "A compound exercise that targets the quadriceps and glutes." },
  { name: "Dumbbell Lunge", categories: ["Legs", "Glute"], equipment_type: "Dumbbell", description: "A compound exercise that targets the quadriceps and glutes." },
  { name: "Dumbbell Squat", categories: ["Legs", "Glute"], equipment_type: "Dumbbell", description: "A compound exercise that targets the lower body." },
  { name: "Hip Thrust", categories: ["Legs", "Glute"], equipment_type: "Barbell", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Leg Extension", categories: ["Legs"], equipment_type: "Machine", description: "An isolation exercise that targets the quadriceps." },
  { name: "Leg Press", categories: ["Legs", "Glute"], equipment_type: "Machine", description: "A compound exercise that targets the lower body." },

  # Back
  { name: "Barbell Bent Over Row", categories: ["Back"], equipment_type: "Barbell", description: "A compound exercise that targets the upper back and lats." },
  { name: "Barbell Deadlift", categories: ["Back", "Legs", "Glute"], equipment_type: "Barbell", description: "A compound exercise that targets the entire back and posterior chain." },
  { name: "Barbell Good Morning", categories: ["Back", "Legs", "Glute"], equipment_type: "Barbell", description: "A compound exercise that targets the lower back and hamstrings." },
  { name: "Barbell Row", categories: ["Back"], equipment_type: "Barbell", description: "A compound exercise that targets the upper back and lats." },
  { name: "Cable Face Pull", categories: ["Back", "Shoulder"], equipment_type: "Cable", description: "An isolation exercise that targets the rear deltoids and upper back." },
  { name: "Cable Lat Pulldown", categories: ["Back"], equipment_type: "Cable", description: "A compound exercise that targets the lats." },
  { name: "Cable Row", categories: ["Back"], equipment_type: "Cable", description: "A compound exercise that targets the upper back and lats." },
  { name: "Chin-Up", categories: ["Back", "Biceps"], equipment_type: "Bodyweight", description: "A compound exercise that targets the lats and biceps." },
  { name: "Dumbbell Bent Over Row", categories: ["Back"], equipment_type: "Dumbbell", description: "A compound exercise that targets the upper back and lats." },
  { name: "Dumbbell Row", categories: ["Back"], equipment_type: "Dumbbell", description: "A compound exercise that targets the upper back and lats." },
  { name: "Inverted Row", categories: ["Back", "Biceps"], equipment_type: "Bodyweight", description: "A compound exercise that targets the upper back and lats." },
  { name: "Lat Pulldown", categories: ["Back"], equipment_type: "Machine", description: "A compound exercise that targets the lats." },
  { name: "Pull-Up", categories: ["Back", "Biceps"], equipment_type: "Bodyweight", description: "A compound exercise that targets the lats and upper back." },
  { name: "Seated Cable Row", categories: ["Back"], equipment_type: "Cable", description: "A compound exercise that targets the upper back and lats." },
  { name: "T-Bar Row", categories: ["Back"], equipment_type: "Barbell", description: "A compound exercise that targets the upper back and lats." },

  # Glute
  { name: "Barbell Hip Thrust", categories: ["Glute", "Legs"], equipment_type: "Barbell", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Barbell Romanian Deadlift", categories: ["Glute", "Legs", "Back"], equipment_type: "Barbell", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Cable Pull Through", categories: ["Glute", "Legs"], equipment_type: "Cable", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Dumbbell Romanian Deadlift", categories: ["Glute", "Legs", "Back"], equipment_type: "Dumbbell", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Glute Bridge", categories: ["Glute"], equipment_type: "Bodyweight", description: "An isolation exercise that targets the glutes." },
  { name: "Hip Abduction", categories: ["Glute"], equipment_type: "Machine", description: "An isolation exercise that targets the gluteus medius." },
  { name: "Hip Extension", categories: ["Glute"], equipment_type: "Machine", description: "An isolation exercise that targets the glutes." },
  { name: "Kettlebell Swing", categories: ["Glute", "Legs", "Back", "Cardio Training"], equipment_type: "Kettlebell", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Lateral Band Walk", categories: ["Glute"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the gluteus medius." },
  { name: "Romanian Deadlift", categories: ["Glute", "Legs", "Back"], equipment_type: "Barbell", description: "A compound exercise that targets the glutes and hamstrings." },
  { name: "Single-Leg Glute Bridge", categories: ["Glute"], equipment_type: "Bodyweight", description: "An isolation exercise that targets the glutes." },
  { name: "Step-Up", categories: ["Glute", "Legs"], equipment_type: "Dumbbell", description: "A compound exercise that targets the glutes and quadriceps." },

  # Abs
  { name: "Ab Wheel Rollout", categories: ["Abs"], equipment_type: "Ab Wheel", description: "A compound exercise that targets the core." },
  { name: "Cable Woodchop", categories: ["Abs"], equipment_type: "Cable", description: "A compound exercise that targets the obliques." },
  { name: "Crunch", categories: ["Abs"], equipment_type: "Bodyweight", description: "An isolation exercise that targets the rectus abdominis." },
  { name: "Dumbbell Side Bend", categories: ["Abs"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the obliques." },
  { name: "Hanging Leg Raise", categories: ["Abs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the lower abs." },
  { name: "Knee Raise", categories: ["Abs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the lower abs." },
  { name: "Plank", categories: ["Abs"], equipment_type: "Bodyweight", description: "An isometric exercise that targets the core." },
  { name: "Russian Twist", categories: ["Abs"], equipment_type: "Dumbbell", description: "A compound exercise that targets the obliques." },
  { name: "Side Plank", categories: ["Abs"], equipment_type: "Bodyweight", description: "An isometric exercise that targets the obliques." },
  { name: "Sit-Up", categories: ["Abs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the rectus abdominis." },
  { name: "Toe Touch", categories: ["Abs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the rectus abdominis." },
  { name: "V-Up", categories: ["Abs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the rectus abdominis." },

  # Calves
  { name: "Calf Raise", categories: ["Calves", "Legs"], equipment_type: "Machine", description: "An isolation exercise that targets the calves." },
  { name: "Donkey Calf Raise", categories: ["Calves", "Legs"], equipment_type: "Machine", description: "An isolation exercise that targets the calves." },
  { name: "Seated Calf Raise", categories: ["Calves", "Legs"], equipment_type: "Machine", description: "An isolation exercise that targets the calves." },
  { name: "Standing Calf Raise", categories: ["Calves", "Legs"], equipment_type: "Machine", description: "An isolation exercise that targets the calves." },

  # Forearm Flexors
  { name: "Barbell Wrist Curl", categories: ["Forearm Flexors"], equipment_type: "Barbell", description: "An isolation exercise that targets the forearm flexors." },
  { name: "Dumbbell Wrist Curl", categories: ["Forearm Flexors"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the forearm flexors." },
  { name: "Farmer's Walk", categories: ["Forearm Flexors", "Back", "Abs"], equipment_type: "Dumbbell", description: "A compound exercise that targets the forearm flexors and grip strength." },
  { name: "Plate Pinch", categories: ["Forearm Flexors"], equipment_type: "Weight Plate", description: "An isolation exercise that targets the forearm flexors and grip strength." },
  { name: "Towel Pull-Up", categories: ["Forearm Flexors", "Back", "Biceps"], equipment_type: "Bodyweight", description: "A compound exercise that targets the forearm flexors and grip strength." },

  # Forearm Extensors
  { name: "Barbell Reverse Wrist Curl", categories: ["Forearm Extensors"], equipment_type: "Barbell", description: "An isolation exercise that targets the forearm extensors." },
  { name: "Dumbbell Reverse Wrist Curl", categories: ["Forearm Extensors"], equipment_type: "Dumbbell", description: "An isolation exercise that targets the forearm extensors." },
  { name: "Finger Extension", categories: ["Forearm Extensors"], equipment_type: "Resistance Band", description: "An isolation exercise that targets the forearm extensors." },
  { name: "Reverse Grip Barbell Curl", categories: ["Forearm Extensors", "Biceps"], equipment_type: "Barbell", description: "A compound exercise that targets the forearm extensors and biceps." },
  { name: "Reverse Grip Dumbbell Curl", categories: ["Forearm Extensors", "Biceps"], equipment_type: "Dumbbell", description: "A compound exercise that targets the forearm extensors and biceps." },

  # Cardio Training
  { name: "Burpee", categories: ["Cardio Training", "Legs", "Chest", "Shoulder"], equipment_type: "Bodyweight", description: "A compound exercise that targets the entire body and cardiovascular system." },
  { name: "High-Intensity Interval Training (HIIT)", categories: ["Cardio Training"], equipment_type: "Bodyweight", description: "A form of cardiovascular exercise that alternates between high-intensity and low-intensity periods." },
  { name: "Jump Rope", categories: ["Cardio Training", "Calves"], equipment_type: "Jump Rope", description: "A compound exercise that targets the cardiovascular system and coordination." },
  { name: "Mountain Climber", categories: ["Cardio Training", "Abs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the core and cardiovascular system." },
  { name: "Running", categories: ["Cardio Training", "Legs"], equipment_type: "Bodyweight", description: "A compound exercise that targets the cardiovascular system and lower body." },
  { name: "Sprint", categories: ["Cardio Training", "Legs"], equipment_type: "Bodyweight", description: "A high-intensity compound exercise that targets the cardiovascular system and lower body." },
  { name: "Swimming", categories: ["Cardio Training", "Back", "Shoulder", "Chest"], equipment_type: "Bodyweight", description: "A compound exercise that targets the entire body and cardiovascular system." },
  { name: "Tabata", categories: ["Cardio Training"], equipment_type: "Bodyweight", description: "A form of high-intensity interval training that alternates between 20 seconds of work and 10 seconds of rest." }
].freeze
# rubocop:enable Layout/LineLength

